### ISSUE TITLE
Assigning player profiles to SkullMeta heads. Bukkit's CraftMetaSkull class does not appear to accept GameProfile directly, and this may require the plugin to be adjusted to support these changes.

### ISSUE THREAD

**Issue by piodois** [DecentSoftware-eu/DecentHolograms#256] opened 2024-11-06 10:40 UTC
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

1. Install DecentHolograms...
2. Do something...
3. Do something else...
4. This happens...

### Server Version

1.21.1

### Client Version

1.21.1

### Plugin Version

2.8.11

### Log

https://pastebin.com/qpHZixEk

**Comment by piodois** [comment] 2024-11-06 10:43
#ICON: PLAYER_HEAD (eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTYzNmRlZTgwNmJhNDdhMmM0MGU5NWI1N2ExMmYzN2RlNmMyZTY3N2YyMTYwMTMyYTA3ZTI0ZWVmZmE2In19fQ==) not work

**Comment by d0by1** [comment] 2024-11-06 10:47
Duplicate of https://github.com/DecentSoftware-eu/DecentHolograms/issues/248

Please actually make sure it's not already known before reporting something.

**Closed by d0by1** 2024-11-06 10:47 UTC
Labels: bug

**Comment by piodois** [comment] 2024-11-06 10:48
but in the previous ones it was for the online mode but this is in premium

**Comment by Andre601** [comment] 2024-11-06 11:18
Online mode and premium are the same.
And the error is the same, so it's a duplicate.
