### ISSUE TITLE
Error throwing on 1.21.1

### ISSUE THREAD

**Issue by JHarris12345** [DecentSoftware-eu/DecentHolograms#254] opened 2024-11-06 00:27 UTC
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

Im not sure how to replicate it throwing but I see this spam a lot:

`[00:26:07 ERROR]: [DecentHolograms] An exception occurred while retrieving skull texture
java.lang.ClassCastException: class net.minecraft.world.item.component.ResolvableProfile cannot be cast to class com.mojang.authlib.GameProfile (net.minecraft.world.item.component.ResolvableProfile and com.mojang.authlib.GameProfile are in unnamed module of loader java.net.URLClassLoader @28ba21f3)
        at DecentHolograms-2.8.11.jar/eu.decentsoftware.holograms.api.utils.items.SkullUtils.getSkullTexture(SkullUtils.java:67) ~[DecentHolograms-2.8.11.jar:?]
        at DecentHolograms-2.8.11.jar/eu.decentsoftware.holograms.api.utils.items.ItemBuilder.getSkullTexture(ItemBuilder.java:313) ~[DecentHolograms-2.8.11.jar:?]
        at DecentHolograms-2.8.11.jar/eu.decentsoftware.holograms.api.utils.items.HologramItem.fromItemStack(HologramItem.java:206) ~[DecentHolograms-2.8.11.jar:?]
        at DecentHolograms-2.8.11.jar/eu.decentsoftware.holograms.api.DHAPI.addHologramLine(DHAPI.java:353) ~[DecentHolograms-2.8.11.jar:?]
        at InsanityCrates-1.0.jar/me.jharris.insanitycrates.holograms.DecentHologramsHologram.appendItemLine(DecentHologramsHologram.java:105) ~[InsanityCrates-1.0.jar:?]
        at InsanityCrates-1.0.jar/me.jharris.insanitycrates.tasks.PrizeHologramAnimation.createHologram(PrizeHologramAnimation.java:128) ~[InsanityCrates-1.0.jar:?]
        at InsanityCrates-1.0.jar/me.jharris.insanitycrates.tasks.PrizeHologramAnimation.run(PrizeHologramAnimation.java:96) ~[InsanityCrates-1.0.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[axolotl-1.21.1.jar:1.21.1-DEV-164e116]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[axolotl-1.21.1.jar:1.21.1-DEV-164e116]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1746) ~[axolotl-1.21.1.jar:1.21.1-DEV-164e116]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[axolotl-1.21.1.jar:1.21.1-DEV-164e116]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1618) ~[axolotl-1.21.1.jar:1.21.1-DEV-164e116]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1318) ~[axolotl-1.21.1.jar:1.21.1-DEV-164e116]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[axolotl-1.21.1.jar:1.21.1-DEV-164e116]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]`

### Server Version

1.21.1

### Client Version

Not sure if it happens to all

### Plugin Version

2.8.11

### Log

N/A

**Comment by Andre601** [comment] 2024-11-06 00:28
Duplicate of #248

Please check existing issues before making one (And close this one please).

**Closed** 2024-11-06 10:51 UTC
Labels: bug
