### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Regomy** [DecentSoftware-eu/DecentHolograms#106] opened 2023-01-20 14:59 UTC
### Just making sure

- [x] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

[17:57:32 WARN]: [DecentHolograms] Plugin DecentHolograms v2.7.9 generated an exception while executing task 902
java.lang.NullPointerException: null
at eu.decentsoftware.holograms.api.holograms.Hologram.lambda$hideClickableEntities$9(Hologram.java:612) ~[?:?]
at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_312]
at eu.decentsoftware.holograms.api.holograms.Hologram.hideClickableEntities(Hologram.java:612) ~[?:?]
at eu.decentsoftware.holograms.api.holograms.Hologram.hide(Hologram.java:568) ~[?:?]
at eu.decentsoftware.holograms.api.holograms.Hologram.onQuit(Hologram.java:398) ~[?:?]
at eu.decentsoftware.holograms.api.holograms.HologramManager.lambda$onQuit$1(HologramManager.java:142) ~[?:?]
at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707) ~[?:1.8.0_312]
at eu.decentsoftware.holograms.api.holograms.HologramManager.onQuit(HologramManager.java:142) ~[?:?]
at eu.decentsoftware.holograms.api.player.PlayerListener.lambda$onQuit$2(PlayerListener.java:32) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Reaper-"1454595"]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.12.2.jar:git-Reaper-"1454595"]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.12.2.jar:git-Reaper-"1454595"]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_312]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_312]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]

### Server Version

his server is running Reaper version git-Reaper-"1454595" (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[18:02:43 INFO]: You are 23 version(s) behind

### Client Version

1.12.2

### Plugin Version

2,7,9

### Log

1

**Comment by SladeHazard** [comment] 2023-01-20 23:16
Duplicate of https://github.com/DecentSoftware-eu/DecentHolograms/issues/102

**Comment by d0by1** [comment] 2023-02-03 16:53
This should be fixed in 2.7.10. Thanks for reporting it!

**Closed by d0by1** 2023-02-03 16:53 UTC
Labels: bug
