### ISSUE TITLE
Something related with Pipeline

### ISSUE THREAD

**Issue by elpersas** [DecentSoftware-eu/DecentHolograms#149] opened 2023-08-05 08:09 UTC
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

It appear suddenly, theres no reason

### Solution

Dont even know

### Server Version

1.19.4

### Client Version

1.19.4

### Plugin Version

2.8.3

### Log

https://pastebin.com/2gRWYt9p

**Comment by c0dingnoobi** [comment] 2023-10-15 03:04
can confirm 
server 1.8.8 and client version 1.7 & 1.8 with [latest commit](https://github.com/DecentSoftware-eu/DecentHolograms/commit/cff509d0db2fd313367f6026f3ebc40b90a4f797)

could not rlly find a way to reproduce except that this happens in 1/50 on join
causes the player to disconnect

**Comment by d0by1** [comment] 2023-11-05 09:32
Hello, I've made some changes to the packet listener, where I addressed this issue. I would really appreciate it if you tested this development version. You can just use it on your server, there shouldn't be any side-effects but I need to know whether or not the changes I made fix this issue and I don't have the capacity to test it in so many environments with so many different players.

You can find this development version on Discord [here](https://discordapp.com/channels/850844430830534696/1170397484653232258). There is a thread created for discussing the version and reporting any issues or any lack of issues.

So please, let me know if this helps and if I get some positive feedback, I will release this version on SpigotMC.

**Comment by c0dingnoobi** [comment] 2023-11-05 13:51
sure

**Comment by d0by1** [comment] 2023-11-09 20:06
> sure, testing it

Have you got any results yet?

**Comment by c0dingnoobi** [comment] 2023-11-10 17:51
no issues so far, running since that day

**Comment by d0by1** [comment] 2023-11-12 09:44
Hello, this issue has been fixed in 2.8.5. Thank you for reporting it!

**Closed by d0by1** 2023-11-12 09:44 UTC
Labels: bug
