### ISSUE TITLE
Fixed hologram rotation, text size, hologram background

### ISSUE THREAD

**Issue by Tuchan** [DecentSoftware-eu/DecentHolograms#140] opened 2023-06-02 19:12 UTC
### Just making sure

- [X] I have read the wiki and made sure, this feature is not yet in the plugin.
- [X] I believe, that this feature is possible to implement.
- [X] I made sure, that this feature has not been requested yet.

### Problem

**Minecraft Limitations**

> ~~Text is always facing the player.~~ 
Text ~~size or~~ font cannot be changed. **It's now possible** 😃 
Some entities make sounds. It only applies to a few entities like the Warden which makes this heartbeat sound.
Icons (#ICON:) are always going to rotate and bob up and down.

![gif preview](https://github.com/DecentSoftware-eu/DecentHolograms/assets/43300571/8b989db0-1844-4f75-8c42-da54ff278bd8)

### Feature

I would like to see that implemented even if it's 1.19.4+ only

### Alternatives

I don't really think there are any other alternatives, you can check [this repo](https://github.com/FancyMcPlugins/FancyHolograms) to see how they did it.

**Comment by Andre601** [comment] 2023-06-02 19:44
We are aware of display entities and your suggestion is a duplicate of #120 more or less.

It's not that we won't add it, but that people (in this case d0by) simply don't have time to implement. Especially given that we would first need to figure out what stuff should be supported and if we can/should have a 1.19.3 and less fallback in place.

**Closed** 2023-06-02 19:48 UTC
